/**
 * Out-of-office / vacation responder — Sieve script generation + validation.
 *
 * Safeguards required by docs/mail-feature-parity-plan.md's destructive-
 * action sign-off section, all enforced here rather than left to app-side
 * scheduling (which this app has no reliable background scheduler for):
 *   1. Mandatory expiry — the date window is checked INSIDE the generated
 *      Sieve script via `currentdate`, so it self-expires at the mail-server
 *      level even if this app is offline. Never "on indefinitely": capped
 *      at MAX_VACATION_DAYS.
 *   2. Sender/domain exclusion list — always includes no-reply/mailing-list
 *      defaults in addition to anything the user adds, on top of Pigeonhole's
 *      own RFC 5230-mandated bulk/list/auto-submitted detection.
 *   3. :days 1 throttles repeat replies to the same sender (anti-loop).
 */

export const DEFAULT_EXCLUDED_SENDER_PATTERNS = [
  "noreply",
  "no-reply",
  "no.reply",
  "donotreply",
  "do-not-reply",
  "mailer-daemon",
  "postmaster",
  "notifications",
  "notification",
];

export const MAX_VACATION_DAYS = 90;

export const VACATION_SCRIPT_NAME = "bluridge-vacation";

export function normalizeExcludedSenders(list: string[]): string[] {
  const cleaned = list.map((s) => s.trim().toLowerCase()).filter(Boolean);
  return Array.from(new Set([...DEFAULT_EXCLUDED_SENDER_PATTERNS, ...cleaned]));
}

export type VacationSettingsInput = {
  subject: string;
  message: string;
  startDate: Date;
  endDate: Date;
  excludedSenders: string[];
  fromAddress: string;
};

/** Throws with a user-facing message if the window is missing/backwards/too long. */
export function validateVacationWindow(startDate: Date, endDate: Date) {
  if (Number.isNaN(startDate.getTime()) || Number.isNaN(endDate.getTime())) {
    throw new Error("Start and end dates are required");
  }
  if (endDate.getTime() <= startDate.getTime()) {
    throw new Error("End date must be after the start date");
  }
  const days = (endDate.getTime() - startDate.getTime()) / 86_400_000;
  if (days > MAX_VACATION_DAYS) {
    throw new Error(
      `Vacation window can't exceed ${MAX_VACATION_DAYS} days — it must have a real end date, not run indefinitely`,
    );
  }
}

function sieveEscape(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/** Sieve's currentdate "date" match-type compares against a plain YYYY-MM-DD string. */
function sieveDate(d: Date): string {
  return d.toISOString().slice(0, 10);
}

/**
 * Builds a self-expiring Sieve script. Validates the window as a side effect
 * (throws before generating anything invalid).
 */
export function buildVacationSieveScript(input: VacationSettingsInput): string {
  validateVacationWindow(input.startDate, input.endDate);
  const excluded = normalizeExcludedSenders(input.excludedSenders);
  const exclusionTests = excluded
    .map((p) => `header :contains "from" "${sieveEscape(p)}"`)
    .join(",\n      ");

  return `require ["vacation", "date", "relational"];

# Generated by BluRidge CEO Command Center — out-of-office responder.
# Self-expiring: only fires between startDate and endDate below, checked
# by the mail server itself regardless of whether the app is running.
if allof(
  currentdate :value "ge" "date" "${sieveDate(input.startDate)}",
  currentdate :value "le" "date" "${sieveDate(input.endDate)}"
) {
  if not anyof(
      ${exclusionTests}
  ) {
    vacation
      :days 1
      :subject "${sieveEscape(input.subject)}"
      :from "${sieveEscape(input.fromAddress)}"
      "${sieveEscape(input.message)}";
  }
}
`;
}
